### ISSUE TITLE
你以为删库然后建小号就行了？

### ISSUE THREAD

**Issue by masterLZ** [opengl106/UCAS-assignments-20#11]
https://github.com/newypei/project_viral_glycoprotein-pjvirgly，链接在这里，垃圾

**Comment by gwsbhqt** [comment]
删repository有用的话，还要git clone干什么呢？

**Comment by loutongbing** [comment]
代码写的不咋地，git也不会用 23333

**Comment by AlaricGilbert** [comment]
不是本人吧这位的github pages的信息和那位对不上

**Comment by loutongbing** [comment]
> 不是本人吧这位的github pages的信息和那位对不上

她自己删了，别人fork了。。（你也不会用git吗狗头）

**Comment by AlaricGilbert** [comment]
> > 不是本人吧这位的github pages的信息和那位对不上
> 
> 她自己删了，别人fork了。。（你也不会用git吗狗头）

这个链接给的不是fork。。应该是第三方保存咯

**Comment by loutongbing** [comment]
> > > 不是本人吧这位的github pages的信息和那位对不上
> > 
> > 
> > 她自己删了，别人fork了。。（你也不会用git吗狗头）
> 
> 这个链接给的不是fork。。应该是第三方保存咯
你fork一下就是这样到你名下了，然后原作者还显示的 不信你看https://github.com/loutongbing/project_viral_glycoprotein-pjvirgly

**Comment by loutongbing** [comment]
> > > 不是本人吧这位的github pages的信息和那位对不上
> > 
> > 
> > 她自己删了，别人fork了。。（你也不会用git吗狗头）
> 
> 这个链接给的不是fork。。应该是第三方保存咯

你fork一下就是这样到你名下了，然后原作者还显示的 不信你看
https://github.com/loutongbing/project_viral_glycoprotein-pjvirgly

**Comment by masterLZ** [comment]
> > > > 不是本人吧这位的github pages的信息和那位对不上
> > > 
> > > 
> > > 她自己删了，别人fork了。。（你也不会用git吗狗头）
> > 
> > 
> > 这个链接给的不是fork。。应该是第三方保存咯
> 
> 你fork一下就是这样到你名下了，然后原作者还显示的 不信你看
> https://github.com/loutongbing/project_viral_glycoprotein-pjvirgly

嗯嗯这个我知道的，只不过fork的这个人，没有上传过别的东西，个人感觉是小号。

**Comment by AlaricGilbert** [comment]
> > > > 不是本人吧这位的github pages的信息和那位对不上
> > > 
> > > 
> > > 她自己删了，别人fork了。。（你也不会用git吗狗头）
> > 
> > 
> > 这个链接给的不是fork。。应该是第三方保存咯
> > 你fork一下就是这样到你名下了，然后原作者还显示的 不信你看https://github.com/loutongbing/project_viral_glycoprotein-pjvirgly


兄弟啊我会用GitHub的
fork是有记录的，我说的是这个人不是直接用的fork是clone之后再自己新开的repo再push上去的

**Comment by loutongbing** [comment]
> > > > > 不是本人吧这位的github pages的信息和那位对不上
> > > > 
> > > > 
> > > > 她自己删了，别人fork了。。（你也不会用git吗狗头）
> > > 
> > > 
> > > 这个链接给的不是fork。。应该是第三方保存咯
> > > 你fork一下就是这样到你名下了，然后原作者还显示的 不信你看https://github.com/loutongbing/project_viral_glycoprotein-pjvirgly
> 
> 兄弟啊我会用GitHub的
> fork是有记录的，我说的是这个人不是直接用的fork是clone之后再自己新开的repo再push上去的

行吧行吧 我也糊涂了

**Comment by MyLovePoppet** [comment]
不会真的有人觉得删库然后建小号就行了吧，不会吧不会吧

**Comment by YouAreSpecialToMe** [comment]
> 不会真的有人觉得删库然后建小号就行了吧，不会吧不会吧

季鬼子给你点灭，🐎都不要了

**Comment by isanyway** [comment]
放一个链接
https://webcache.googleusercontent.com/search?q=cache:H4sVqd4MGDoJ:https://github.com/opengl106/project_viral_glycoprotein-pjvirgly

**Comment by ESUAdmin** [comment]
多谢你一直平反八九六四，感谢你支持郭文贵先生革命，支持光复香港、时代革命，感谢支持新中华联邦，您上次发送来的关于习近平家族海外转移资产的巴拿马文件很有用，感谢各位对中国民主革命作出的贡献！
