### ISSUE TITLE
哥们这代码水平咋混进国科大的，给个门路呗

### ISSUE THREAD

**Issue by GengchenXU** [opengl106/UCAS-assignments-20#16]

**Comment by unikcc** [comment]
u1s1，人家再说也是河南高考裸分稳上浙大的，当然这不妨碍他死了🐴

**Comment by sxy1998123** [comment]
本科生亲身经历，很多计算机硕士代码能力不一定很强，有的是靠研究和解决问题出名的

**Comment by GengchenXU** [comment]
> 本科生亲身经历，很多计算机硕士代码能力不一定很强，有的是靠研究和解决问题出名的

怎么说呢，知乎扒他的你应该也看了，这家伙代码一看就是复制的啊。我也是本科生，我也知道我们水平跟他这代码差不多，但是我们没和他抄还这么个水平

**Comment by GengchenXU** [comment]
> u1s1，人家再说也是河南高考裸分稳上浙大的，当然这不妨碍他死了🐴

你是不是跟勃呆萌搞混了

**Comment by sxy1998123** [comment]
> > u1s1，人家再说也是河南高考裸分稳上浙大的，当然这不妨碍他死了🐴
> 
> 你是不是跟勃呆萌搞混了

我当然知道这家伙没有🐴，来这里就是围观他的。我的本意就是想说计算机研究生不一定要写一手好代码，能解决问题也可以。但当研究生的前提是有道德，有修养，很显然这个人没有。

**Comment by nepleo** [comment]
> > 本科生亲身经历，很多计算机硕士代码能力不一定很强，有的是靠研究和解决问题出名的
> 
> 怎么说呢，知乎扒他的你应该也看了，这家伙代码一看就是复制的啊。我也是本科生，我也知道我们水平跟他这代码差不多，但是我们没和他抄还这么个水平

仔细看，他的代码里还用了goto ，额，属实把我整蒙了。

**Comment by 514DNA** [comment]
> > > 本科生亲身经历，很多计算机硕士代码能力不一定很强，有的是靠研究和解决问题出名的
> > 
> > 
> > 怎么说呢，知乎扒他的你应该也看了，这家伙代码一看就是复制的啊。我也是本科生，我也知道我们水平跟他这代码差不多，但是我们没和他抄还这么个水平
> 
> 仔细看，他的代码里还用了goto ，额，属实把我整蒙了。

这就是太君独到的理解么，真是有够好笑的呢
