### ISSUE TITLE
大家冷静点，别给GitHub引流！！！

### ISSUE THREAD

**Issue by Centauria** [opengl106/UCAS-assignments-20#22]
难道大家没发现Github渐渐的已经快连不上了吗
像这种危险的操作暴露给zf
只会增大gfw墙掉GitHub的可能性

建议截图传播完事，不要暴露地址

**Comment by rechangshengshou** [comment]
怕什么，13年15年都干过仗，还不是能上

**Comment by GengchenXU** [comment]
> 难道大家没发现Github渐渐的已经快连不上了吗
> 像这种危险的操作暴露给zf
> 只会增大gfw墙掉GitHub的可能性
> 
> 建议截图传播完事，不要暴露地址

要墙的话，这登github的强度早墙了。估计在白名单里吧
