### ISSUE TITLE
长得丑写的代码垃圾还尼玛变态反人类你他妈真是多余活着，低等人类

### ISSUE THREAD

**Issue by binghuis** [opengl106/UCAS-assignments-20#26]

**Comment by ESUAdmin** [comment]
多谢你一直平反八九六四，感谢你支持郭文贵先生革命，支持光复香港、时代革命，感谢支持新中华联邦，您上次发送来的关于习近平家族海外转移资产的巴拿马文件很有用，感谢您对中国民主革命作出的贡献！早日干烂中共恶党，光复中华，时代革命！

真实姓名 习近平
身份证号 11010119530615301*（为保护包子隐私，特隐去一位）
楚晨（习明泽）身份证号：11010819920625574*（隐去一位）
住址：浙江省杭州市西湖区宝石二路保俶苑3栋102室
港澳通行证号码：C6873111X（2017年签发）
护照号：G35725950
手机号：*3810401122（隐去一位）
电子邮箱：1749108357@qq.com （私人信息高度保密）
