### ISSUE TITLE
怎么有这么多NT在HEIP

### ISSUE THREAD

**Issue by ESUAdmin** [opengl106/UCAS-assignments-20#36]
请恁们自行拨打新疆集中营收容热线，谢谢！

**Comment by tamaki-3hs25rk** [comment]
**你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！滚！**

**Comment by tamaki-3hs25rk** [comment]
> 请恁们自行拨打新疆集中营收容热线，谢谢！

**你这个进化不完全的生命体，基因突变的外星人，幼稚园程度的高中生，先天蒙古症的青蛙头，圣母峰雪人的弃婴，化粪池堵塞的凶手，非洲人搞上黑猪的後裔，阴阳失调的黑猩猩，被诺亚方舟压过的河马，新火山喷发口，超大无耻传声扩音喇叭，爱斯基摩人的耻辱，和蟑螂共存活的超个体，生命力腐烂的半植物，会发出臭味的垃圾人，唾弃名词的源头，每天退化三次的恐龙，人类历史上最强的废材，上帝失手摔下来的旧洗衣机，能思考的无脑袋生物，损毁亚洲同胞名声的祸害，祖先为之蒙羞的子孙，沉积千年的腐植质，科学家也不敢研究的原始物种，宇宙毁灭必备的原料，连半兽人都瞧不起你的半兽人，10倍石油浓度的沉积原料，被毁容的麦当劳叔叔！**

**Comment by tamaki-3hs25rk** [comment]
> 请恁们自行拨打新疆集中营收容热线，谢谢！

**绞你妈的屄 老子把你妈绞在树上 傻屄东西 肏你妈的屄 你他妈给老子吃屎 你妈个臭屄 傻屄东西 你他妈四个人你叫 叫你妈个屄土东西 你个弱智 老子把你妈干翻 把你妈干在地上叫我爸爸 跪下来舔我包皮 傻屄东西 你只有一句话 只有肏你妈妈 啊 你只有肏你妈 还有别的话吗 你妈了个臭屄 说话说你妈个屄我 傻屄东西 傻屄 你妈屄你是什么弱智东西啊 你闭嘴好不好 你除了肏你妈 还有什么 还有什么 你除了肏你妈还有什么 你妈被我奸杀你不知道吗兄弟 你知道你妈被我奸杀了吗**

**Comment by ESUAdmin** [comment]
笑死我了，自己瞎骂自己赞，小废物们的自尊心都这么脆弱的吗？

球球你了不要再复制粘贴了，这样一点意思都没，和孙狗抽象圣经一样，真的傻批

**Comment by caicaizii** [comment]
> 笑死我了，自己瞎骂自己赞，小废物们的自尊心都这么脆弱的吗？
> 
> 球球你了不要再复制粘贴了，这样一点意思都没，和孙狗抽象圣经一样，真的傻批

南波灣 南波灣

**Comment by mirrorb** [comment]
@ESUAdmin 
大家都在给季子越桑上坟。我看你和季桑互follow想必很交好吧，看到这么多人来上坟我很是欣慰。你也很悲痛吧，毕竟你俩志同道合，季桑上路也没回到故乡看sakura，你多回去看看吧，也算让季桑放下心灵的寄托。

**Comment by trotsky1997** [comment]
> 笑死我了，自己瞎骂自己赞，小废物们的自尊心都这么脆弱的吗？
> 
> 球球你了不要再复制粘贴了，这样一点意思都没，和孙狗抽象圣经一样，真的傻批

弱智气急败坏了,多舔点,季太君就给你口了

**Comment by ESUAdmin** [comment]
小废物们，大爹宣布你们胜利了！你们又胜利了奥

这下不会再来黑屁了吧？你野爹乐的就是你，，，

**Comment by mirrorb** [comment]
日本宣布无条件投降？9月2号时间还挺讲究😄
